### ISSUE TITLE
Why Jetty 7?

### ISSUE THREAD

**Issue by si14** [lynaghk/jetty7-websockets-async#4]
I can't understand why Jetty 7 is still used so widely. Is there any particular reason besides ring-jetty-adapter (which can be replaced by [newer one](https://github.com/sunng87/ring-jetty9-adapter))?

**Comment by lynaghk** [comment]
As far as I can tell, Jetty 7 is still maintained and it's widely used.
If it's not broken, don't fix it = )

Re: Jetty 9, I actually tried extensively to use its websockets functionality, but the interface is very Java-bloated (forced implementation inheritance, something that forces you to use the REPL-unfriendly `gen-class`, &c.) and difficult to work with in Clojure compared to Jetty 7's websocket interface.

**Comment by si14** [comment]
Thank you for the answer.

As a side note: why not http-kit then?

**Comment by lynaghk** [comment]
Also looked at http-kit.
We'd run into some inconsistencies building a proxy server with http-kit, and in general I'd prefer to stick with more widely used software (e.g., Jetty) over newer stuff unless there is a compelling reason to be bleeding edge.
http-kit's value proposition (small, readable source code, no dependencies) didn't mesh with our use cases.

That said, you could probably build something like this library backed by http-kit in about 15 minutes with judicious use of copy/paste = )

**Comment by si14** [comment]
I see. Just wondered about your experience with it, actually :)

**Comment by si14** [comment]
Thank you for the answer!
