### ISSUE TITLE
How to reject user before handshake completes?

### ISSUE THREAD

**Issue by NoamB** [lynaghk/jetty7-websockets-async#5]
Hi,
1st - Thanks for this project.

2nd - I want the user to login first using a normal HTTP request, then authenticate using the session-cookie to the websocket handler. It seems I only have the request in hand after the handshake was already over and successful. Is there a way to reject the user early (status 403 for example) before the handshake completes?

Also, if you already let the handshake complete, and you exchange some messages with the client, but then you want to close the socket, how is this done?

Thanks.

**Comment by lynaghk** [comment]
I'm not sure about the authentication---all of our deployments are on private secured networks.
I know that newer versions of Nginx do websocket forwarding, so you may be able to handle auth though that.
Otherwise, your answer probably lies deep within the JavaDocs: http://download.eclipse.org/jetty/stable-7/apidocs/

If you do find a solution that works within this codebase, I'd be happy to review it and possibly merge it in.

Re: closing, you can just call `core.async/close!` on the input channel to terminate the connection.

**Comment by NoamB** [comment]
Thanks for the quick response. 
'close!' works great.
Regarding the authentication, I'll see if I can figure it out, and if so, will post it here.
Meanwhile I have a working hack where I pass the request through all my ring middleware stack, and extract the session map out of there to be used by the on-message handlers. It's ugly and i'll try to replace it with something nicer.

You can close this or keep it open as you see fit.

**Comment by lynaghk** [comment]
Okay, closing for now, but if you find a nice solution please do post it.

**Comment by NoamB** [comment]
OK - the flow is this:

In WebSocketHandler - first `handle` is called, which calls `acceptWebSocket`.

Inside `acceptWebSocket` we have a call to `checkOrigin` and later a call to `doWebSocketConnect`.

`doWebSocketConnect` is expected to return a `WebSocket` instance and if it doesn't, a generic error will be returned by `acceptWebSocket` (HttpServletResponse.SC_SERVICE_UNAVAILABLE).

So part of the solution is to allow the developer to hook into `doWebSocketConnect` and on some condition make it return null. This can be done in similar fashion to how middleware is injected today to the normal Jetty handler in ring-jetty-adapter:

```
(defn- proxy-handler
  "Returns an Jetty Handler implementation for the given Ring handler."
  [handler]
  (proxy [AbstractHandler] []
    (handle [_ ^Request base-request request response]
      (let [request-map  (servlet/build-request-map request)
            response-map (handler request-map)]
        (when response-map
          (servlet/update-servlet-response response response-map)
          (.setHandled base-request true))))))
```

You pass your handler in, run it against the request, and can conclude from the response if you should return a `WebSocket` or null, which will reject the user.

For example, if the developer handler doesn't return 200 for the request passed, we return null.

Source:
http://grepcode.com/file/repo1.maven.org/maven2/org.eclipse.jetty.aggregate/jetty-websocket/7.6.11.v20130520/org/eclipse/jetty/websocket/WebSocketFactory.java#WebSocketFactory
