### ISSUE TITLE
Adding websockets to existing Ring App

### ISSUE THREAD

**Issue by deaddowney** [lynaghk/jetty7-websockets-async#7]
Is it possible to add a websocket handler to an existing Ring app?  It's not clear from the documentation.    I would like to serve up certain paths with WS and others with straight HTTP.  If this is not a good idea, what would you recommend in terms of structuring the routes?

**Comment by lynaghk** [comment]
Yep, the websockets are setup via Jetty's configurator option; you can continue to use your plain ol' HTTP handler.
